spring:
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres

#spring.datasource:
#  hikari.maxium-pool-size: 4
#  url: jdbc:postgresql://ec2-54-163-140-5.compute-1.amazonaws.com:5432/de3cestlqkekp0
#  username: u7bjqnltofpp1p
#  password: p240170e441a1aa72fee6bba192898a83e9c30edf1f7aeb94329e15e34bc3dc2c
#  driver-class-name: org.postgresql.Driver
spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-34-194-158-176.compute-1.amazonaws.com:5432/d2qlllo1jm5ij1
  username: drktaleyslswsc
  password: 04390ee83ba4eecb68725e819a790562dcda88e7286439eeef155b144eb74dc8
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000