spring:
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: postgres

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-52-3-200-138.compute-1.amazonaws.com/d7bjks1c43p2ga
  username: ilguwqxlhhdega
  password: 6a1f55e4c6e35f6ce056655f867f73152c993aa60d078d60a809413976d2b926
  driver-class-name: org.postgresql.Driver